server:
  port: 8083
  ssl:
    key-store: mykeystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: adidas-challenge

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: true

